Add methods for PropertyQueryTaskWriter, Mock Plugin
wooga/gradle-commons-test pull request #9
Opened 2022-03-04 13:47 UTC by Azurelol

## Description

- Add newer methods for propety_query_task:.
- Adds a mock plugin to be used when testing these testing APIs.

## Changes
* ![ADD] PropertyQueryTaskWriter : IsNull, isNotNull, isTrue, isFalse, equals
* ![ADD] MockPlugin : For testing APIs that work on tasks

[NEW]:      https://resources.atlas.wooga.com/icons/icon_new.svg "New"
[ADD]:      https://resources.atlas.wooga.com/icons/icon_add.svg "Add"
[IMPROVE]:  https://resources.atlas.wooga.com/icons/icon_improve.svg "Improve"
[CHANGE]:   https://resources.atlas.wooga.com/icons/icon_change.svg "Change"
[FIX]:      https://resources.atlas.wooga.com/icons/icon_fix.svg "Fix"
[UPDATE]:   https://resources.atlas.wooga.com/icons/icon_update.svg "Update"
[BREAK]:    https://resources.atlas.wooga.com/icons/icon_break.svg "Remove"
[REMOVE]:   https://resources.atlas.wooga.com/icons/icon_remove.svg "Remove"
[IOS]:      https://resources.atlas.wooga.com/icons/icon_iOS.svg "iOS"
[ANDROID]:  https://resources.atlas.wooga.com/icons/icon_android.svg "Android"
[WEBGL]:    https://resources.atlas.wooga.com/icons/icon_webGL.svg "WebGL"
[GRADLE]:   https://resources.atlas.wooga.com/icons/icon_gradle.svg "GRADLE"
[UNITY]:    https://resources.atlas.wooga.com/icons/icon_unity.svg "Unity"
[LINUX]:    https://resources.atlas.wooga.com/icons/icon_linux.svg "Linux"
[WIN]:      https://resources.atlas.wooga.com/icons/icon_windows.svg "Windows"
[MACOS]:    https://resources.atlas.wooga.com/icons/icon_iOS.svg "macOS"

2022-03-16 10:00 UTC, Larusso reviewed
These are two patches or?
You also did changes to `wrapValueBasedOnType` which I don't see the context for in this PR

2022-03-29 07:31 UTC, Larusso requested changes

2022-03-29 07:31 UTC, Larusso commented on src/main/groovy/com/wooga/gradle/test/IntegrationSpec.groovy
> +            // ...
these comments give me nothing. Mostly because I can easily decuce from the code what it does.

2022-03-29 07:31 UTC, Larusso commented on src/main/groovy/com/wooga/gradle/test/PropertyQueryTaskWriter.groovy
> +     * @deprecated Use {@code equals} instead
That is not the correct deprecation annotation. Add `@Deprecated` to the method. In java there is sadly no field to set a message.

2022-03-29 09:29 UTC, Azurelol commented on src/main/groovy/com/wooga/gradle/test/IntegrationSpec.groovy
> +            // ...
Very well.

2022-03-29 09:29 UTC, Azurelol commented on src/main/groovy/com/wooga/gradle/test/PropertyQueryTaskWriter.groovy
> +     * @deprecated Use {@code equals} instead
I see, my bad. 
I ended up removing this method since there will be no "equals" on the newer object API.

2022-03-29 09:40 UTC, Larusso approved these changes

2022-03-29 09:45 UTC, merged